/**
 * App lifecycle: launch / attach / stop, device listing, driver-shim setup,
 * and app-id detection. Wraps the Dart MCP server's launch_app /
 * connect_dart_tooling_daemon / stop_app and persists per-session app state.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import { pathToFileURL } from "node:url";
import { callTool, FlutterAxiError } from "./client.js";
import {
  clearAppState,
  platformForDeviceId,
  readAppState,
  writeAppState,
  type AppState,
  type Platform,
} from "./appstate.js";

export const DRIVER_SHIM_RELPATH = join("lib", "flutter_axi_main.dart");

export const DRIVER_SHIM_CONTENT = `// Generated by flutter-axi (\`setup driver\`). Launch entrypoint that enables
// the Flutter Driver extension so flutter-axi can drive the app. Safe to
// regenerate; do not edit.
import 'package:flutter_driver/driver_extension.dart';

import 'main.dart' as app;

void main() {
  enableFlutterDriverExtension();
  app.main();
}
`;

// --- Devices ---

export interface DeviceInfo {
  id: string;
  name: string;
  platform: string;
  emulator: boolean;
}

export function parseDevicesList(json: string): DeviceInfo[] {
  try {
    const parsed = JSON.parse(json) as {
      devices?: {
        id?: unknown;
        name?: unknown;
        targetPlatform?: unknown;
        emulator?: unknown;
      }[];
    };
    if (!Array.isArray(parsed.devices)) return [];
    return parsed.devices.map((d) => ({
      id: String(d.id ?? ""),
      name: String(d.name ?? ""),
      platform: String(d.targetPlatform ?? ""),
      emulator: d.emulator === true,
    }));
  } catch {
    return [];
  }
}

/**
 * Register a project root with the Dart MCP server. Required before
 * launch_app / list_devices work: the server only operates under registered
 * roots and discovers the Flutter SDK through them. Idempotent; roots are
 * re-registered on every call because a recycled bridge starts empty.
 */
export async function addRoot(root: string, session?: string): Promise<void> {
  await callTool(
    "add_roots",
    { roots: [{ uri: pathToFileURL(root).href }] },
    { session },
  );
}

/**
 * Best-effort root for commands that need one before any app is launched
 * (`devices`): the cwd when it is a Flutter project, else the last launched
 * project recorded in the session's app state.
 */
export function candidateRoot(session?: string): string | null {
  if (existsSync(join(process.cwd(), "pubspec.yaml"))) return process.cwd();
  const state = readAppState(session);
  return state?.projectRoot ?? null;
}

export async function listDevices(session?: string): Promise<DeviceInfo[]> {
  const root = candidateRoot(session);
  if (root) await addRoot(root, session);
  const raw = await callTool("list_devices", {}, { session });
  return parseDevicesList(raw);
}

// --- Driver shim setup ---

export interface SetupDriverResult {
  shimWritten: boolean;
  pubspecUpdated: boolean;
}

/**
 * Idempotently prepare a Flutter project for driver input: ensure
 * flutter_driver is a dev dependency and write the shim entrypoint that
 * calls enableFlutterDriverExtension() before the app's real main().
 */
export function setupDriver(root: string): SetupDriverResult {
  const pubspecPath = join(root, "pubspec.yaml");
  if (!existsSync(pubspecPath)) {
    throw new FlutterAxiError(
      `Not a Flutter project: ${pubspecPath} does not exist`,
      "VALIDATION_ERROR",
      ["Pass the Flutter project root: flutter-axi setup driver <root>"],
    );
  }

  let pubspecUpdated = false;
  const pubspec = readFileSync(pubspecPath, "utf-8");
  if (!/^\s*flutter_driver\s*:/m.test(pubspec)) {
    const devDepsMatch = pubspec.match(/^dev_dependencies:\s*$/m);
    if (!devDepsMatch || devDepsMatch.index === undefined) {
      throw new FlutterAxiError(
        "Could not find a dev_dependencies section in pubspec.yaml",
        "VALIDATION_ERROR",
        [
          "Add manually:\n  dev_dependencies:\n    flutter_driver:\n      sdk: flutter",
        ],
      );
    }
    const insertAt = devDepsMatch.index + devDepsMatch[0].length;
    const updated =
      pubspec.slice(0, insertAt) +
      "\n  flutter_driver:\n    sdk: flutter" +
      pubspec.slice(insertAt);
    writeFileSync(pubspecPath, updated);
    pubspecUpdated = true;
  }

  const shimPath = join(root, DRIVER_SHIM_RELPATH);
  let shimWritten = false;
  if (
    !existsSync(shimPath) ||
    readFileSync(shimPath, "utf-8") !== DRIVER_SHIM_CONTENT
  ) {
    writeFileSync(shimPath, DRIVER_SHIM_CONTENT);
    shimWritten = true;
  }

  return { shimWritten, pubspecUpdated };
}

export function hasDriverShim(root: string): boolean {
  return existsSync(join(root, DRIVER_SHIM_RELPATH));
}

// --- App id detection ---

/**
 * Best-effort app id detection from the project's platform files. Android:
 * applicationId in android/app/build.gradle(.kts). iOS:
 * PRODUCT_BUNDLE_IDENTIFIER in the Runner pbxproj.
 */
export function detectAppId(root: string, platform: Platform): string | null {
  try {
    if (platform === "android") {
      for (const gradle of ["build.gradle.kts", "build.gradle"]) {
        const path = join(root, "android", "app", gradle);
        if (!existsSync(path)) continue;
        const content = readFileSync(path, "utf-8");
        const m = content.match(/applicationId\s*[=(]?\s*["']([^"']+)["']/);
        if (m) return m[1];
      }
      return null;
    }
    if (platform === "ios") {
      const path = join(root, "ios", "Runner.xcodeproj", "project.pbxproj");
      if (!existsSync(path)) return null;
      const content = readFileSync(path, "utf-8");
      const m = content.match(/PRODUCT_BUNDLE_IDENTIFIER\s*=\s*([^;\s]+);/);
      if (m) return m[1].replace(/"/g, "");
      return null;
    }
  } catch {
    return null;
  }
  return null;
}

// --- Launch / attach / stop ---

export interface LaunchOptions {
  device?: string;
  target?: string;
  appId?: string;
  session?: string;
  /** Skip the driver shim even when present. */
  noDriver?: boolean;
}

export interface LaunchResult {
  pid: number;
  dtdUri: string;
  deviceId: string;
  platform: Platform;
  appId: string | null;
  /** True when the app was launched through the driver shim entrypoint. */
  driverEnabled: boolean;
}

export function parseLaunchOutput(raw: string): { dtdUri: string; pid: number } {
  try {
    const parsed = JSON.parse(raw) as { dtdUri?: unknown; pid?: unknown };
    if (typeof parsed.dtdUri === "string" && typeof parsed.pid === "number") {
      return { dtdUri: parsed.dtdUri, pid: parsed.pid };
    }
  } catch {
    // fall through
  }
  throw new FlutterAxiError(
    `Launch failed: ${raw.slice(0, 400)}`,
    "DRIVER_ERROR",
    [
      "Run `flutter-axi devices` to verify the device id",
      "Check the project builds: flutter build <platform> in the project root",
    ],
  );
}

/** First app launch compiles the project - allow plenty of time. */
const LAUNCH_TIMEOUT_MS = 600_000;

export async function launchApp(
  root: string,
  opts: LaunchOptions = {},
): Promise<LaunchResult> {
  if (!existsSync(join(root, "pubspec.yaml"))) {
    throw new FlutterAxiError(
      `Not a Flutter project: ${root}`,
      "VALIDATION_ERROR",
      ["Pass the Flutter project root: flutter-axi launch <root> --device <id>"],
    );
  }

  const device = opts.device ?? process.env.FLUTTER_AXI_DEVICE;
  if (!device) {
    throw new FlutterAxiError("Missing device id", "VALIDATION_ERROR", [
      "Run `flutter-axi devices` to list devices, then `flutter-axi launch <root> --device <id>`",
      "Or set FLUTTER_AXI_DEVICE to a default device id",
    ]);
  }

  // Prefer the driver shim so flutter_driver input works out of the box.
  let target = opts.target;
  let driverEnabled = false;
  if (!target && !opts.noDriver && hasDriverShim(root)) {
    target = DRIVER_SHIM_RELPATH;
    driverEnabled = true;
  } else if (target && basename(target) === basename(DRIVER_SHIM_RELPATH)) {
    driverEnabled = true;
  }

  await addRoot(root, opts.session);

  const args: Record<string, unknown> = { root, device };
  if (target) args.target = target;
  const raw = await callTool("launch_app", args, {
    session: opts.session,
    timeoutMs: LAUNCH_TIMEOUT_MS,
  });
  const { dtdUri, pid } = parseLaunchOutput(raw);

  await callTool(
    "connect_dart_tooling_daemon",
    { uri: dtdUri },
    { session: opts.session },
  );

  const platform = platformForDeviceId(device);
  const appId = opts.appId ?? detectAppId(root, platform);

  const state: AppState = {
    pid,
    dtdUri,
    deviceId: device,
    platform,
    appId,
    projectRoot: root,
    launchedAt: new Date().toISOString(),
  };
  writeAppState(state, opts.session);

  return { pid, dtdUri, deviceId: device, platform, appId, driverEnabled };
}

export interface AttachOptions {
  dtdUri: string;
  session?: string;
}

/**
 * Attach to an already-running app by DTD URI. Inspection-only: driver input,
 * logs, and stop only work for apps started via launch.
 */
export async function attachApp(opts: AttachOptions): Promise<void> {
  await callTool(
    "connect_dart_tooling_daemon",
    { uri: opts.dtdUri },
    { session: opts.session },
  );
  const prev = readAppState(opts.session);
  writeAppState(
    {
      pid: prev?.pid ?? null,
      dtdUri: opts.dtdUri,
      deviceId: prev?.deviceId ?? null,
      platform: prev?.platform ?? "unknown",
      appId: prev?.appId ?? null,
      projectRoot: prev?.projectRoot ?? null,
      launchedAt: new Date().toISOString(),
    },
    opts.session,
  );
}

/**
 * Stop the session's launched app. Idempotent: no app recorded, or an
 * already-dead pid, is a no-op success.
 */
export async function stopApp(session?: string): Promise<boolean> {
  const state = readAppState(session);
  if (!state || state.pid === null) return false;
  try {
    await callTool("stop_app", { pid: state.pid }, { session });
  } catch {
    // Already gone - idempotent no-op.
  }
  clearAppState(session);
  return true;
}
